## 
## -------------------------------------------------------------
##    Copyright 2010-2011 Cadence
##    All Rights Reserved Worldwide
## 
##    Licensed under the Apache License, Version 2.0 (the
##    "License"); you may not use this file except in
##    compliance with the License.  You may obtain a copy of
##    the License at
## 
##        http://www.apache.org/licenses/LICENSE-2.0
## 
##    Unless required by applicable law or agreed to in
##    writing, software distributed under the License is
##    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
##    CONDITIONS OF ANY KIND, either express or implied.  See
##    the License for the specific language governing
##    permissions and limitations under the License.
## -------------------------------------------------------------
## 

OC_DIR = ../../common/oc_ethernet_rtl

include $(UVM_HOME)/examples/Makefile.ius

all: uvm_reg_mem_built_in_seq uvm_reg_mem_hdl_paths_seq


IRUN=$(IUS) -define SINGLE_RAM_VARIABLE -define RAM128x64 -define USE_SLICE_API \
	-incdir ../common/wishbone -incdir ../common/oc_ethernet_rtl \
 	-incdir $(UVM_HOME)/examples/simple/registers/common/wishbone \
	-incdir $(OC_DIR) \
	-F $(OC_DIR)/rtl_file_list.lst \
	tb_top.sv tb_env.sv

help:
	@echo " Available run-time targets:"
	@echo
	@echo " Built-In Tests:"
	@echo
	@echo "    uvm_reg_hw_reset_seq"
	@echo "    uvm_reg_access_seq"
	@echo "    uvm_mem_access_seq"
	@echo "    uvm_reg_bit_bash_seq"
	@echo "    uvm_mem_walk_seq"
	@echo "    uvm_reg_access_seq     (e.g. uvm_reg_access_seq+uvm_mem_access_seq)"
	@echo "    uvm_reg_mem_built_in_seq   (e.g. all the built-in tests)"
	@echo

uvm_%_seq:
	@echo "using uvmhome $(UVM_HOME)"
	$(IRUN) +UVM_SEQUENCE=$@
	$(CHECK)

