#!/bin/sh

if [ $1 = clean ]
then
  rm -rf work vsim.wlf transcript
  exit
fi

if [ $1 ]
then
  SEQ=$1
else
echo ""
echo " Usage: run_questa <name_of_sequence>"
echo ""
echo "    Example:"
echo ""
echo "    run_questa uvm_ral_built_in_seq"
echo ""
echo " Available sequences:"
echo ""
echo " Built-In RAL:"
echo ""
echo "    uvm_ral_hw_reset_seq"
echo "    uvm_ral_reg_access_seq"
echo "    uvm_ral_mem_access_seq"
echo "    uvm_ral_bit_bash_seq"
echo "    uvm_ral_mem_walk_seq"
echo "    uvm_ral_access_seq     runs both uvm_ral_reg_access_seq and uvm_ral_mem_access_seq"
echo "    uvm_ral_built_in_seq   runs all the built-in tests"
echo ""
exit
fi

./simv +UVM_SEQUENCE=$SEQ
