## 
## -------------------------------------------------------------
##    Copyright 2010-2011 Mentor Graphics Corporation
##    All Rights Reserved Worldwide
## 
##    Licensed under the Apache License, Version 2.0 (the
##    "License"); you may not use this file except in
##    compliance with the License.  You may obtain a copy of
##    the License at
## 
##        http://www.apache.org/licenses/LICENSE-2.0
## 
##    Unless required by applicable law or agreed to in
##    writing, software distributed under the License is
##    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
##    CONDITIONS OF ANY KIND, either express or implied.  See
##    the License for the specific language governing
##    permissions and limitations under the License.
## -------------------------------------------------------------
## 
USES_DPI = 1

include $(UVM_HOME)/examples/Makefile.questa


all: run

comp : prepare
	# compile UVM
	vlog -timescale "1ns/1ns" \
             +acc=rmb \
             -mfcu \
             -suppress 2181 \
             +incdir+$(UVM_HOME)/src \
             $(UVM_HOME)/src/uvm_pkg.sv -incr
	
	# compile USER CODE
	vlog -timescale "1ns/1ns" \
             -mfcu \
             -suppress 2181 \
             +acc=rmb \
             $(UVM_HOME)/src/uvm_macros.svh \
             +incdir+$(UVM_HOME)/src \
             +incdir+../common/apb \
             +define+NUM_REGS=10 \
             test1.sv

run: comp
	vsim +UVM_VERBOSITY=HIGH \
             -sv_lib $(UVM_HOME)/lib/uvm_dpi \
             -c \
             -do "run -all; q" \
             -l questa.log \
             +UVM_TESTNAME=test \
             testm
	$(CHECK)


