## 
## -------------------------------------------------------------
##    Copyright 2010-2011 Cadence
##    All Rights Reserved Worldwide
## 
##    Licensed under the Apache License, Version 2.0 (the
##    "License"); you may not use this file except in
##    compliance with the License.  You may obtain a copy of
##    the License at
## 
##        http://www.apache.org/licenses/LICENSE-2.0
## 
##    Unless required by applicable law or agreed to in
##    writing, software distributed under the License is
##    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
##    CONDITIONS OF ANY KIND, either express or implied.  See
##    the License for the specific language governing
##    permissions and limitations under the License.
## -------------------------------------------------------------
## 

#
# compiles uvm_pkg and test.sv in two different compile scopes 
# requires that uvm_macros.svh really provide all symbols
# well this cannot be checked but for instance `UVM_REG_DATA_WIDTH was missing before
#
all: 
	vcs -R -sverilog +incdir+$(UVM_HOME)/src $(UVM_HOME)/src/uvm_pkg.sv $(UVM_HOME)/src/dpi/uvm_dpi.cc +acc +vpi -CFLAGS -DVCS +UVM_TESTNAME=test +UVM_VERBOSITY=HIGH +define+NUM_REGS=10 test1.sv
	$(CHECK)
