#!/bin/sh

if [ $1 = clean ]
then
  rm -rf work vsim.wlf transcript
  exit
fi

if [ $1 ]
then
  SEQ=$1
else
echo ""
echo " Usage: run_questa <name_of_sequence>"
echo ""
echo "    Example:"
echo ""
echo "    run_questa uvm_reg_mem_built_in_seq"
echo ""
echo " Available sequences:"
echo ""
echo " Built-In Tests:"
echo ""
echo "    uvm_reg_mem_built_in_seq (run all)"
echo "       uvm_reg_hw_reset_seq"
echo "       uvm_reg_bit_bash_seq"
echo "       uvm_mem_walk_seq"
echo "       uvm_reg_access_seq)"
echo "          uvm_reg_access_seq"
echo "          uvm_reg_mem_access_seq"
echo ""
exit
fi

VSIM_ARGS='tb_top tb -c -sv_lib ../../../lib/libuvm_questa +ROOT_HDL_PATH=tb_top.dut'


vlib work
vlog -f compile_questa.f
vsim $VSIM_ARGS -do "run -all;q" +UVM_SEQUENCE=$SEQ

