## 
## -------------------------------------------------------------
##    Copyright 2010-2011 Cadence
##    All Rights Reserved Worldwide
## 
##    Licensed under the Apache License, Version 2.0 (the
##    "License"); you may not use this file except in
##    compliance with the License.  You may obtain a copy of
##    the License at
## 
##        http://www.apache.org/licenses/LICENSE-2.0
## 
##    Unless required by applicable law or agreed to in
##    writing, software distributed under the License is
##    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
##    CONDITIONS OF ANY KIND, either express or implied.  See
##    the License for the specific language governing
##    permissions and limitations under the License.
## -------------------------------------------------------------
## 

IRUN=irun -uvmhome $(UVM_HOME) testfile.sv

include $(UVM_HOME)/examples/Makefile.ius

all: test1 test2

test1: 
	$(IRUN) +UVM_TESTNAME=test -define UVM_NO_DPI
	$(CHECK)
	$(IRUN) -f test.f -define UVM_NO_DPI
	$(CHECK)
	$(IRUN) -F test.f -define UVM_NO_DPI
	$(CHECK)

test2:
	$(IRUN) +UVM_TESTNAME=test
	$(CHECK)
	$(IRUN) -f test.f
	$(CHECK)
	$(IRUN) -F test.f
	$(CHECK)
