## 
## -------------------------------------------------------------
##    Copyright 2011 Synopsys
##    All Rights Reserved Worldwide
## 
##    Licensed under the Apache License, Version 2.0 (the
##    "License"); you may not use this file except in
##    compliance with the License.  You may obtain a copy of
##    the License at
## 
##        http://www.apache.org/licenses/LICENSE-2.0
## 
##    Unless required by applicable law or agreed to in
##    writing, software distributed under the License is
##    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
##    CONDITIONS OF ANY KIND, either express or implied.  See
##    the License for the specific language governing
##    permissions and limitations under the License.
## -------------------------------------------------------------
## 

UVM_HOME = ../../../distrib

include $(UVM_HOME)/examples/Makefile.questa

all:  test_dpi test_no_dpi

test_no_dpi: prepare
	make -f Makefile.questa UVM_NO_DPI=1 test_dpi
	
test_dpi: prepare
	$(VLOG) testfile.sv
	$(VSIM) +UVM_TESTNAME=test 
	$(CHECK)
	
	$(VLOG) testfile.sv
	$(VSIM) -f test.f 
	$(CHECK)
