## 
## -------------------------------------------------------------
##    Copyright 2011 Synopsys
##    All Rights Reserved Worldwide
## 
##    Licensed under the Apache License, Version 2.0 (the
##    "License"); you may not use this file except in
##    compliance with the License.  You may obtain a copy of
##    the License at
## 
##        http://www.apache.org/licenses/LICENSE-2.0
## 
##    Unless required by applicable law or agreed to in
##    writing, software distributed under the License is
##    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
##    CONDITIONS OF ANY KIND, either express or implied.  See
##    the License for the specific language governing
##    permissions and limitations under the License.
## -------------------------------------------------------------
## 

TOOL= vcs -sverilog -timescale=1ns/1ns \
        +acc +vpi \
        +incdir+$(UVM_HOME)/src $(UVM_HOME)/src/uvm.sv \
        $(UVM_HOME)/src/dpi/uvm_dpi.cc -CFLAGS -DVCS \
	testfile.sv

include $(UVM_HOME)/examples/Makefile.vcs

all:  test2 test1

test1: 
	$(TOOL) +define+UVM_NO_DPI
	./simv -l vcs.log  +UVM_TESTNAME=test 
	$(CHECK)
	$(TOOL) +define+UVM_NO_DPI
	./simv -l vcs.log  -f test.f 
	$(CHECK)

test2:
	$(TOOL) 
	./simv -l vcs.log +UVM_TESTNAME=test
	$(CHECK)
	$(TOOL) 
	./simv -l vcs.log -f test.f
	$(CHECK)
