## 
## -------------------------------------------------------------
##    Copyright 2011 Mentor Graphics Corporation
##    Copyright 2011 Synopsys, Inc.
##    All Rights Reserved Worldwide
## 
##    Licensed under the Apache License, Version 2.0 (the
##    "License"); you may not use this file except in
##    compliance with the License.  You may obtain a copy of
##    the License at
## 
##        http://www.apache.org/licenses/LICENSE-2.0
## 
##    Unless required by applicable law or agreed to in
##    writing, software distributed under the License is
##    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
##    CONDITIONS OF ANY KIND, either express or implied.  See
##    the License for the specific language governing
##    permissions and limitations under the License.
## -------------------------------------------------------------
## 

include $(UVM_HOME)/examples/Makefile.vcs

all: run

comp:
	$(VCS) +incdir+. top.sv

run: comp
	$(SIMV) +FILE=./run_func_A.log +FUNC
	$(SIMV) +FILE=./run_func_B.log +FUNC +DESTABLE
	$(SIMV) +FILE=./run_task_A.log
	$(SIMV) +FILE=./run_task_B.log +DESTABLE
	diff ./run_func_A.log ./run_func_B.log ;
	diff ./run_task_A.log ./run_task_B.log 
