#!/bin/sh

if [ $1 = clean ]
then
  rm -rf work vsim.wlf transcript
  exit
fi

if [ $1 ]
then
  option=$1
else
echo ""
echo " Usage: run_questa <list_of_sequences>"
echo ""
echo " List of sequences must be separated by commas and contain no whitespace."
echo ""
echo "    run_questa uvm_reg_mem_built_in_seq,mem_init_from_file_seq"
echo ""
echo " Available sequences:"
echo ""
echo " Built-Ins:"
echo ""
echo "    uvm_reg_hw_reset_seq"
echo "    uvm_reg_access_seq"
echo "    uvm_mem_access_seq"
echo "    uvm_reg_bit_bash_seq"
echo "    uvm_mem_walk_seq"
echo "    uvm_reg_mem_access_seq     runs both uvm_reg_access_seq and uvm_mem_access_seq"
echo "    uvm_reg_mem_built_in_seq   runs all the built-in tests"
echo ""
echo " User-defined:"
echo ""
echo "    incr_read_byte_seq"
echo "    incr_write_byte_seq"
echo "    incr_read_write_read_seq"
echo "    r8_w8_r4_w4_seq"
echo "    read_modify_write_seq"
echo "    loop_read_modify_write_seq"
echo ""
echo "    mem_init_from_file_seq"
echo "    mem_rand_init_seq"
echo "    user_acp_reg_seq"
echo "    virtual_seq"
echo ""
exit
fi

VSIM_ARGS="-novopt -c -sv_lib ../../../../lib/Linux_x86_64/libuvm_questa xbus_reg_tb_top"

vlib work
vlog -f compile_questa.f

vsim $VSIM_ARGS -do "run -all; q" +UVM_SEQUENCE=$option +UVM_TESTNAME=cmd_line_seq_test +UVM_VERBOSITY=HIGH
