#!/bin/sh

if [ "$1" ]
then
  option=$1
else

echo ""
echo " Usage: run_ius <list_of_sequences>"
echo ""
echo " List of sequences must be separated by commas and contain no whitespace."
echo ""
echo "    run_vcs uvm_reg_mem_built_in_seq,mem_init_from_file_seq"
echo ""
echo " Available sequences:"
echo ""
echo " Built-Ins:"
echo ""
echo "    uvm_reg_hw_reset_seq"
echo "    uvm_reg_access_seq"
echo "    uvm_mem_access_seq"
echo "    uvm_reg_bit_bash_seq"
echo "    uvm_mem_walk_seq"
echo "    uvm_reg_mem_access_seq     runs both uvm_reg_access_seq and uvm_mem_access_seq"
echo "    uvm_reg_mem_built_in_seq   runs all the built-in tests"
echo ""
echo " User-defined:"
echo ""
echo "    mem_init_from_file_seq"
echo "    mem_rand_init_seq"
echo "    user_acp_reg_seq"
echo "    virtual_seq"
echo ""
exit
fi

irun -f ../direct_virt_seq/compile_ius.f +UVM_SEQUENCE=$option +UVM_TESTNAME=cmd_line_seq_test
